/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppVideosRouteImport } from './routes/_app.videos'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiMediaMediaIdRouteImport } from './routes/api.media.$mediaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaMediaIdRoute = ApiMediaMediaIdRouteImport.update({
  id: '/api/media/$mediaId',
  path: '/api/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/videos': typeof AppVideosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/videos': typeof AppVideosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/videos': typeof AppVideosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/videos' | '/api/auth/$' | '/api/media/$mediaId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/videos' | '/api/auth/$' | '/api/media/$mediaId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/videos'
    | '/api/auth/$'
    | '/api/media/$mediaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaMediaIdRoute: typeof ApiMediaMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/videos': {
      id: '/_app/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$mediaId': {
      id: '/api/media/$mediaId'
      path: '/api/media/$mediaId'
      fullPath: '/api/media/$mediaId'
      preLoaderRoute: typeof ApiMediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppVideosRoute: typeof AppVideosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppVideosRoute: AppVideosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaMediaIdRoute: ApiMediaMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
