/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppFilesRouteImport } from './routes/_app.files'
import { Route as AppVideosRouteImport } from './routes/_app.videos'
import { Route as SharedFilesTokenRouteImport } from './routes/shared-files.$token'
import { Route as AppVideosVideoIdRouteImport } from './routes/_app.videos_.$videoId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiSharedFilesTokenRouteImport } from './routes/api.shared-files.$token'
import { Route as AppVideosVideoIdCompareRouteImport } from './routes/_app.videos_.$videoId_.compare'
import { Route as ApiVideosVideoIdMediaRouteImport } from './routes/api.videos.$videoId.media'
import { Route as ApiVideosVideoIdUploadsRouteImport } from './routes/api.videos.$videoId.uploads'
import { Route as ApiVideosVideoIdMediaFileIdRouteImport } from './routes/api.videos.$videoId.media.$fileId'
import { Route as ApiVideosVideoIdUploadsUploadIdRouteImport } from './routes/api.videos.$videoId.uploads.$uploadId'
import { Route as ApiVideosVideoIdUploadsUploadIdCompleteRouteImport } from './routes/api.videos.$videoId.uploads.$uploadId.complete'
import { Route as ApiVideosVideoIdUploadsUploadIdPartsPartNumberRouteImport } from './routes/api.videos.$videoId.uploads.$uploadId.parts.$partNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppRoute,
} as any)
const SharedFilesTokenRoute = SharedFilesTokenRouteImport.update({
  id: '/shared-files/$token',
  path: '/shared-files/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideosVideoIdRoute = AppVideosVideoIdRouteImport.update({
  id: '/videos_/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharedFilesTokenRoute = ApiSharedFilesTokenRouteImport.update({
  id: '/api/shared-files/$token',
  path: '/api/shared-files/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideosVideoIdCompareRoute = AppVideosVideoIdCompareRouteImport.update({
  id: '/videos_/$videoId_/compare',
  path: '/videos/$videoId/compare',
  getParentRoute: () => AppRoute,
} as any)
const ApiVideosVideoIdMediaRoute = ApiVideosVideoIdMediaRouteImport.update({
  id: '/api/videos/$videoId/media',
  path: '/api/videos/$videoId/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosVideoIdUploadsRoute = ApiVideosVideoIdUploadsRouteImport.update({
  id: '/api/videos/$videoId/uploads',
  path: '/api/videos/$videoId/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosVideoIdMediaFileIdRoute =
  ApiVideosVideoIdMediaFileIdRouteImport.update({
    id: '/$fileId',
    path: '/$fileId',
    getParentRoute: () => ApiVideosVideoIdMediaRoute,
  } as any)
const ApiVideosVideoIdUploadsUploadIdRoute =
  ApiVideosVideoIdUploadsUploadIdRouteImport.update({
    id: '/$uploadId',
    path: '/$uploadId',
    getParentRoute: () => ApiVideosVideoIdUploadsRoute,
  } as any)
const ApiVideosVideoIdUploadsUploadIdCompleteRoute =
  ApiVideosVideoIdUploadsUploadIdCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiVideosVideoIdUploadsUploadIdRoute,
  } as any)
const ApiVideosVideoIdUploadsUploadIdPartsPartNumberRoute =
  ApiVideosVideoIdUploadsUploadIdPartsPartNumberRouteImport.update({
    id: '/parts/$partNumber',
    path: '/parts/$partNumber',
    getParentRoute: () => ApiVideosVideoIdUploadsUploadIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof AppFilesRoute
  '/videos': typeof AppVideosRoute
  '/shared-files/$token': typeof SharedFilesTokenRoute
  '/videos/$videoId': typeof AppVideosVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shared-files/$token': typeof ApiSharedFilesTokenRoute
  '/videos/$videoId/compare': typeof AppVideosVideoIdCompareRoute
  '/api/videos/$videoId/media': typeof ApiVideosVideoIdMediaRouteWithChildren
  '/api/videos/$videoId/uploads': typeof ApiVideosVideoIdUploadsRouteWithChildren
  '/api/videos/$videoId/media/$fileId': typeof ApiVideosVideoIdMediaFileIdRoute
  '/api/videos/$videoId/uploads/$uploadId': typeof ApiVideosVideoIdUploadsUploadIdRouteWithChildren
  '/api/videos/$videoId/uploads/$uploadId/complete': typeof ApiVideosVideoIdUploadsUploadIdCompleteRoute
  '/api/videos/$videoId/uploads/$uploadId/parts/$partNumber': typeof ApiVideosVideoIdUploadsUploadIdPartsPartNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof AppFilesRoute
  '/videos': typeof AppVideosRoute
  '/shared-files/$token': typeof SharedFilesTokenRoute
  '/videos/$videoId': typeof AppVideosVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shared-files/$token': typeof ApiSharedFilesTokenRoute
  '/videos/$videoId/compare': typeof AppVideosVideoIdCompareRoute
  '/api/videos/$videoId/media': typeof ApiVideosVideoIdMediaRouteWithChildren
  '/api/videos/$videoId/uploads': typeof ApiVideosVideoIdUploadsRouteWithChildren
  '/api/videos/$videoId/media/$fileId': typeof ApiVideosVideoIdMediaFileIdRoute
  '/api/videos/$videoId/uploads/$uploadId': typeof ApiVideosVideoIdUploadsUploadIdRouteWithChildren
  '/api/videos/$videoId/uploads/$uploadId/complete': typeof ApiVideosVideoIdUploadsUploadIdCompleteRoute
  '/api/videos/$videoId/uploads/$uploadId/parts/$partNumber': typeof ApiVideosVideoIdUploadsUploadIdPartsPartNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/files': typeof AppFilesRoute
  '/_app/videos': typeof AppVideosRoute
  '/shared-files/$token': typeof SharedFilesTokenRoute
  '/_app/videos_/$videoId': typeof AppVideosVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shared-files/$token': typeof ApiSharedFilesTokenRoute
  '/_app/videos_/$videoId_/compare': typeof AppVideosVideoIdCompareRoute
  '/api/videos/$videoId/media': typeof ApiVideosVideoIdMediaRouteWithChildren
  '/api/videos/$videoId/uploads': typeof ApiVideosVideoIdUploadsRouteWithChildren
  '/api/videos/$videoId/media/$fileId': typeof ApiVideosVideoIdMediaFileIdRoute
  '/api/videos/$videoId/uploads/$uploadId': typeof ApiVideosVideoIdUploadsUploadIdRouteWithChildren
  '/api/videos/$videoId/uploads/$uploadId/complete': typeof ApiVideosVideoIdUploadsUploadIdCompleteRoute
  '/api/videos/$videoId/uploads/$uploadId/parts/$partNumber': typeof ApiVideosVideoIdUploadsUploadIdPartsPartNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/videos'
    | '/shared-files/$token'
    | '/videos/$videoId'
    | '/api/auth/$'
    | '/api/shared-files/$token'
    | '/videos/$videoId/compare'
    | '/api/videos/$videoId/media'
    | '/api/videos/$videoId/uploads'
    | '/api/videos/$videoId/media/$fileId'
    | '/api/videos/$videoId/uploads/$uploadId'
    | '/api/videos/$videoId/uploads/$uploadId/complete'
    | '/api/videos/$videoId/uploads/$uploadId/parts/$partNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/videos'
    | '/shared-files/$token'
    | '/videos/$videoId'
    | '/api/auth/$'
    | '/api/shared-files/$token'
    | '/videos/$videoId/compare'
    | '/api/videos/$videoId/media'
    | '/api/videos/$videoId/uploads'
    | '/api/videos/$videoId/media/$fileId'
    | '/api/videos/$videoId/uploads/$uploadId'
    | '/api/videos/$videoId/uploads/$uploadId/complete'
    | '/api/videos/$videoId/uploads/$uploadId/parts/$partNumber'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/files'
    | '/_app/videos'
    | '/shared-files/$token'
    | '/_app/videos_/$videoId'
    | '/api/auth/$'
    | '/api/shared-files/$token'
    | '/_app/videos_/$videoId_/compare'
    | '/api/videos/$videoId/media'
    | '/api/videos/$videoId/uploads'
    | '/api/videos/$videoId/media/$fileId'
    | '/api/videos/$videoId/uploads/$uploadId'
    | '/api/videos/$videoId/uploads/$uploadId/complete'
    | '/api/videos/$videoId/uploads/$uploadId/parts/$partNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SharedFilesTokenRoute: typeof SharedFilesTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSharedFilesTokenRoute: typeof ApiSharedFilesTokenRoute
  ApiVideosVideoIdMediaRoute: typeof ApiVideosVideoIdMediaRouteWithChildren
  ApiVideosVideoIdUploadsRoute: typeof ApiVideosVideoIdUploadsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/videos': {
      id: '/_app/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/shared-files/$token': {
      id: '/shared-files/$token'
      path: '/shared-files/$token'
      fullPath: '/shared-files/$token'
      preLoaderRoute: typeof SharedFilesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/videos_/$videoId': {
      id: '/_app/videos_/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof AppVideosVideoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shared-files/$token': {
      id: '/api/shared-files/$token'
      path: '/api/shared-files/$token'
      fullPath: '/api/shared-files/$token'
      preLoaderRoute: typeof ApiSharedFilesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/videos_/$videoId_/compare': {
      id: '/_app/videos_/$videoId_/compare'
      path: '/videos/$videoId/compare'
      fullPath: '/videos/$videoId/compare'
      preLoaderRoute: typeof AppVideosVideoIdCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/videos/$videoId/media': {
      id: '/api/videos/$videoId/media'
      path: '/api/videos/$videoId/media'
      fullPath: '/api/videos/$videoId/media'
      preLoaderRoute: typeof ApiVideosVideoIdMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/$videoId/uploads': {
      id: '/api/videos/$videoId/uploads'
      path: '/api/videos/$videoId/uploads'
      fullPath: '/api/videos/$videoId/uploads'
      preLoaderRoute: typeof ApiVideosVideoIdUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/$videoId/media/$fileId': {
      id: '/api/videos/$videoId/media/$fileId'
      path: '/$fileId'
      fullPath: '/api/videos/$videoId/media/$fileId'
      preLoaderRoute: typeof ApiVideosVideoIdMediaFileIdRouteImport
      parentRoute: typeof ApiVideosVideoIdMediaRoute
    }
    '/api/videos/$videoId/uploads/$uploadId': {
      id: '/api/videos/$videoId/uploads/$uploadId'
      path: '/$uploadId'
      fullPath: '/api/videos/$videoId/uploads/$uploadId'
      preLoaderRoute: typeof ApiVideosVideoIdUploadsUploadIdRouteImport
      parentRoute: typeof ApiVideosVideoIdUploadsRoute
    }
    '/api/videos/$videoId/uploads/$uploadId/complete': {
      id: '/api/videos/$videoId/uploads/$uploadId/complete'
      path: '/complete'
      fullPath: '/api/videos/$videoId/uploads/$uploadId/complete'
      preLoaderRoute: typeof ApiVideosVideoIdUploadsUploadIdCompleteRouteImport
      parentRoute: typeof ApiVideosVideoIdUploadsUploadIdRoute
    }
    '/api/videos/$videoId/uploads/$uploadId/parts/$partNumber': {
      id: '/api/videos/$videoId/uploads/$uploadId/parts/$partNumber'
      path: '/parts/$partNumber'
      fullPath: '/api/videos/$videoId/uploads/$uploadId/parts/$partNumber'
      preLoaderRoute: typeof ApiVideosVideoIdUploadsUploadIdPartsPartNumberRouteImport
      parentRoute: typeof ApiVideosVideoIdUploadsUploadIdRoute
    }
  }
}

interface AppRouteChildren {
  AppFilesRoute: typeof AppFilesRoute
  AppVideosRoute: typeof AppVideosRoute
  AppVideosVideoIdRoute: typeof AppVideosVideoIdRoute
  AppVideosVideoIdCompareRoute: typeof AppVideosVideoIdCompareRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFilesRoute: AppFilesRoute,
  AppVideosRoute: AppVideosRoute,
  AppVideosVideoIdRoute: AppVideosVideoIdRoute,
  AppVideosVideoIdCompareRoute: AppVideosVideoIdCompareRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiVideosVideoIdMediaRouteChildren {
  ApiVideosVideoIdMediaFileIdRoute: typeof ApiVideosVideoIdMediaFileIdRoute
}

const ApiVideosVideoIdMediaRouteChildren: ApiVideosVideoIdMediaRouteChildren = {
  ApiVideosVideoIdMediaFileIdRoute: ApiVideosVideoIdMediaFileIdRoute,
}

const ApiVideosVideoIdMediaRouteWithChildren =
  ApiVideosVideoIdMediaRoute._addFileChildren(
    ApiVideosVideoIdMediaRouteChildren,
  )

interface ApiVideosVideoIdUploadsUploadIdRouteChildren {
  ApiVideosVideoIdUploadsUploadIdCompleteRoute: typeof ApiVideosVideoIdUploadsUploadIdCompleteRoute
  ApiVideosVideoIdUploadsUploadIdPartsPartNumberRoute: typeof ApiVideosVideoIdUploadsUploadIdPartsPartNumberRoute
}

const ApiVideosVideoIdUploadsUploadIdRouteChildren: ApiVideosVideoIdUploadsUploadIdRouteChildren =
  {
    ApiVideosVideoIdUploadsUploadIdCompleteRoute:
      ApiVideosVideoIdUploadsUploadIdCompleteRoute,
    ApiVideosVideoIdUploadsUploadIdPartsPartNumberRoute:
      ApiVideosVideoIdUploadsUploadIdPartsPartNumberRoute,
  }

const ApiVideosVideoIdUploadsUploadIdRouteWithChildren =
  ApiVideosVideoIdUploadsUploadIdRoute._addFileChildren(
    ApiVideosVideoIdUploadsUploadIdRouteChildren,
  )

interface ApiVideosVideoIdUploadsRouteChildren {
  ApiVideosVideoIdUploadsUploadIdRoute: typeof ApiVideosVideoIdUploadsUploadIdRouteWithChildren
}

const ApiVideosVideoIdUploadsRouteChildren: ApiVideosVideoIdUploadsRouteChildren =
  {
    ApiVideosVideoIdUploadsUploadIdRoute:
      ApiVideosVideoIdUploadsUploadIdRouteWithChildren,
  }

const ApiVideosVideoIdUploadsRouteWithChildren =
  ApiVideosVideoIdUploadsRoute._addFileChildren(
    ApiVideosVideoIdUploadsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SharedFilesTokenRoute: SharedFilesTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSharedFilesTokenRoute: ApiSharedFilesTokenRoute,
  ApiVideosVideoIdMediaRoute: ApiVideosVideoIdMediaRouteWithChildren,
  ApiVideosVideoIdUploadsRoute: ApiVideosVideoIdUploadsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
